<?php
// This file serves CSS but is generated by PHP so the colours/font from
// district.php are automatically applied everywhere.
// Include in HTML with: <link rel="stylesheet" href="style.css.php">
// NOTE: the colour/status keyword names (groen/geel/oranje/rood/grijs)
// are shared internal identifiers used by matching CSS classes here and
// by the JS/PHP that generates them elsewhere — see the translation note
// near the top of config.php for why these aren't renamed yet.
require_once __DIR__ . '/district.php';
header('Content-Type: text/css; charset=utf-8');

function hex_to_rgb($hex) {
    $hex = ltrim($hex, '#');
    return [hexdec(substr($hex, 0, 2)), hexdec(substr($hex, 2, 2)), hexdec(substr($hex, 4, 2))];
}
function mix($hex, $targetRgb, $amount) {
    [$r, $g, $b] = hex_to_rgb($hex);
    $nr = round($r + ($targetRgb[0] - $r) * $amount);
    $ng = round($g + ($targetRgb[1] - $g) * $amount);
    $nb = round($b + ($targetRgb[2] - $b) * $amount);
    return sprintf('#%02x%02x%02x', $nr, $ng, $nb);
}

$primary = COLOR_PRIMARY;
$light20 = mix($primary, [255, 255, 255], 0.20);
$light50 = mix($primary, [255, 255, 255], 0.50);
$light85 = mix($primary, [255, 255, 255], 0.85);
$light95 = mix($primary, [255, 255, 255], 0.95);
$dark15  = mix($primary, [0, 0, 0], 0.15);
$dark30  = mix($primary, [0, 0, 0], 0.30);
?>
:root {
  --primary: <?= $primary ?>;
  --primary-light-20: <?= $light20 ?>;
  --primary-light-50: <?= $light50 ?>;
  --primary-light-85: <?= $light85 ?>;
  --primary-light-95: <?= $light95 ?>;
  --primary-dark-15: <?= $dark15 ?>;
  --primary-dark-30: <?= $dark30 ?>;
  --white: #ffffff;
  --ink: #1c2321;
  --grey: #6b7573;
  --border: #e2e6e4;

  --status-groen: #2f8f4e;
  --status-geel: #d4a417;
  --status-oranje: #e07a2f;
  --status-rood: #c9432f;
  --status-grijs: #9aa3a0;

  --font: <?= FONT_FAMILY ?>;
}

* { box-sizing: border-box; }
body {
  margin: 0; font-family: var(--font); background: var(--primary-light-95); color: var(--ink);
}
a { color: var(--primary); }

.topbar {
  background: var(--primary); color: var(--white); padding: 14px 24px;
  display: flex; align-items: center; justify-content: space-between;
}
.topbar .brand { display: flex; align-items: center; gap: 10px; font-weight: 600; font-size: 16px; }
.topbar .district { font-weight: 400; opacity: .85; font-size: 13px; }
.topbar nav a { color: var(--white); text-decoration: none; margin-left: 18px; font-size: 13.5px; opacity: .9; }
.topbar nav a:hover { opacity: 1; text-decoration: underline; }

.container { max-width: 1180px; margin: 0 auto; padding: 24px; }

.grid-6 {
  display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 28px;
}
@media (max-width: 900px) { .grid-6 { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 600px) { .grid-6 { grid-template-columns: 1fr; } }

.category-card {
  background: var(--white); border: 1px solid var(--border); border-radius: 12px; padding: 18px;
}
.category-card h3 {
  margin: 0 0 12px; font-size: 15.5px; color: var(--primary); display: flex; align-items: center; gap: 8px;
}
.category-card .sub-buttons { display: flex; flex-wrap: wrap; gap: 6px; }
.category-card .sub-buttons button, .category-card .sub-buttons a.sub-btn {
  background: var(--primary-light-95); border: 1px solid var(--primary-light-85); color: var(--primary-dark-15);
  border-radius: 7px; padding: 6px 10px; font-size: 12.5px; cursor: pointer; text-decoration: none; font-family: var(--font);
}
.category-card .sub-buttons button:hover, .category-card .sub-buttons a.sub-btn:hover { background: var(--primary-light-85); }
.category-card.soon { opacity: .55; }
.category-card.soon .sub-buttons button { cursor: not-allowed; }

.card { background: var(--white); border: 1px solid var(--border); border-radius: 12px; padding: 18px; }

.status-dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 6px; }
.status-dot.groen { background: var(--status-groen); }
.status-dot.geel { background: var(--status-geel); }
.status-dot.oranje { background: var(--status-oranje); }
.status-dot.rood { background: var(--status-rood); }
.status-dot.grijs { background: var(--status-grijs); }

.badge {
  display: inline-block; padding: 2px 9px; border-radius: 20px; font-size: 11.5px; font-weight: 600;
}
.badge.groen { background: #e6f4ea; color: var(--status-groen); }
.badge.geel { background: #fbf1da; color: var(--status-geel); }
.badge.oranje { background: #fbe9dc; color: var(--status-oranje); }
.badge.rood { background: #f9e3df; color: var(--status-rood); }
.badge.grijs { background: #eef0ef; color: var(--status-grijs); }

button.primary, a.btn-primary {
  background: var(--primary); color: var(--white); border: none; border-radius: 7px; padding: 9px 16px;
  font-size: 13.5px; font-weight: 600; cursor: pointer; font-family: var(--font); text-decoration: none; display: inline-block;
}
button.primary:hover, a.btn-primary:hover { background: var(--primary-dark-15); }
button.secondary {
  background: var(--white); color: var(--primary); border: 1px solid var(--primary-light-50); border-radius: 7px;
  padding: 9px 16px; font-size: 13.5px; font-weight: 600; cursor: pointer; font-family: var(--font);
}

input, select, textarea {
  border: 1px solid var(--border); border-radius: 7px; padding: 8px 10px; font-size: 13.5px; font-family: var(--font);
  width: 100%; outline: none;
}
input:focus, select:focus, textarea:focus { border-color: var(--primary); }
label { font-size: 12.5px; color: var(--grey); display: block; margin: 10px 0 3px; }

table { width: 100%; border-collapse: collapse; font-size: 13.5px; }
table th { text-align: left; color: var(--grey); font-weight: 600; font-size: 12px; padding: 8px 10px; border-bottom: 1px solid var(--border); }
table td { padding: 10px; border-bottom: 1px solid var(--border); vertical-align: middle; }
table tr:hover td { background: var(--primary-light-95); cursor: pointer; }

.modal-backdrop {
  position: fixed; inset: 0; background: rgba(0,0,0,.4); display: flex; align-items: flex-start;
  justify-content: center; padding: 40px 16px; overflow-y: auto; z-index: 50;
}
.modal { background: var(--white); border-radius: 12px; padding: 24px; width: 100%; max-width: 560px; }
.modal h2 { margin-top: 0; color: var(--primary); font-size: 17px; }
.modal-close { float: right; background: none; border: none; font-size: 18px; cursor: pointer; color: var(--grey); }

.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0 12px; }
.form-grid .full { grid-column: 1 / -1; }
.checkbox-row { display: flex; align-items: center; gap: 8px; margin: 8px 0; }
.checkbox-row input { width: auto; }

#map { height: 380px; border-radius: 12px; overflow: hidden; border: 1px solid var(--border); }

.activity-item { border-left: 2px solid var(--primary-light-50); padding: 4px 0 12px 14px; margin-left: 4px; position: relative; }
.activity-item::before { content: ''; position: absolute; left: -5px; top: 6px; width: 8px; height: 8px; border-radius: 50%; background: var(--primary); }
.activity-item .meta { font-size: 11.5px; color: var(--grey); }

.feed-item { display: flex; gap: 10px; padding: 8px 0; border-bottom: 1px solid var(--border); font-size: 13px; }
.feed-item .tijd { color: var(--grey); font-size: 11.5px; white-space: nowrap; }

.toolbar { display: flex; justify-content: space-between; align-items: center; gap: 10px; margin-bottom: 14px; flex-wrap: wrap; }
.toolbar .right { display: flex; gap: 8px; }
